# Generated by Django 2.2.1 on 2019-06-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20190607_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(help_text='author name', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(help_text='about the book', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(help_text='genre', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='title here', max_length=50),
        ),
    ]
